-- ============================================================================
-- SAYARIQ SYSTEM — SCHEMA LEGACY (DEPRECADO)
-- ============================================================================
-- Este archivo contenía el schema original con 13+ tablas.
-- Ha sido reemplazado por el schema limpio V2.
--
-- ► El nuevo schema está en: database/sayariq_v2.sql
--
-- El nuevo schema tiene:
--   · 10 tablas limpias (vs 13+ tablas + views + triggers + stored procedures)
--   · 5 módulos: Personas, Almacén, Pedidos, Kardex, Liquidaciones
--   · 0 views, 0 triggers, 0 stored procedures
--   · Foreign keys correctas con orden de creación validado
--   · Datos semilla de categorías/calidades incluidos
--
-- Para crear la nueva base de datos ejecute:
--   mysql -u root -p < database/sayariq_v2.sql
-- ============================================================================
